package com.ocmseservice.apiservice.workflows.urapg.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Model class for URA Payment Gateway request
 */
@Data
@NoArgsConstructor
public class UraPaymentRequest {
    
    /**
     * Notice number for the parking fine
     */
    private String noticeNo;
    
    /**
     * Vehicle registration number
     */
    private String vehicleNo;
    
    /**
     * Amount to be paid
     */
    private BigDecimal amountPayable;
    
    /**
     * PP code for the parking fine
     */
    private String ppCode;
    
    /**
     * User ID (from SingPass/CorpPass)
     */
    private String userId;
    
    /**
     * Transaction reference number (generated by the system)
     */
    private String transactionRef;
    
    /**
     * URL to redirect after successful payment
     */
    private String successUrl;
    
    /**
     * URL to redirect after failed payment
     */
    private String failureUrl;
    
    /**
     * URL for callback notification from payment gateway
     */
    private String callbackUrl;
}
