package com.ocmseservice.apiservice.workflows.spcp.model;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.io.Serializable;

/**
 * Response model for application transaction ID creation
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect
@Getter
@Setter
@SuperBuilder
@AllArgsConstructor
@NoArgsConstructor
public class AuthAppTxnIdResponse implements Serializable {

    private static final long serialVersionUID = 1L;
    
    /**
     * Response code from the authentication service
     */
    private String responseCode;
    
    /**
     * Response message from the authentication service
     */
    private String responseMsg;
    
    /**
     * Application transaction ID generated by the authentication service
     */
    private String appTxnId;
}
